name: AI Job Recruiter V4

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run job agent
        run: python main.py

      - name: Show generated files
        run: ls -R

      - name: Create frontend folder
        run: mkdir -p frontend

      - name: Copy jobs.json to frontend
        run: cp jobs.json frontend/jobs.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jobs-output
          path: jobs.json

      - name: Commit & push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add jobs.json frontend/jobs.json
          git commit -m "update jobs feed" || echo "no changes"
          git push
